fric-frac-laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('eventcategory', 'EventCategoryController');
Route::resource('eventtopic', 'EventTopicController');
Route::resource('role', 'RoleController');
Route::resource('country', 'CountryController');
Route::resource('person', 'PersonController');
Route::resource('user', 'UserController');
Route::resource('event', 'EventController');

fric-frac-laravel/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

fric-frac-laravel/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Person;
use App\Role;
use App\User;
use App\Userinfo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Userinfo::all();
        return view('user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $persons = Person::all();
        $roles = Role::all();
        return view('user.create', compact('persons', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'person_id' => 'required',
            'role_id' => 'required',
            'salt' => 'required',
            'hashedpassword' => 'required',
        ]);

        Userinfo::create($request->all());
        return redirect()->route('user.index')

            ->with('success', 'User created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Userinfo  $userinfo
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Userinfo::find($id);

        return view('user.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Userinfo  $userinfo
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Userinfo::find($id);
        $persons = Person::all();
        $roles = Role::all();

        return view('user.edit', compact('item', 'persons', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Userinfo  $userinfo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'person_id' => 'required',
            'role_id' => 'required',
            'salt' => 'required',
            'hashedpassword' => 'required',
        ]);

        $update = [
            'name' => $request->name,
            'person_id' => $request->person_id,
            'role_id' => $request->role_id,
            'salt' => $request->salt,
            'hashedpassword' => $request->hashedpassword,
        ];

        Userinfo::where('id',$id)->update($update);

        return Redirect::to(route('user.index'))
            ->with('success', 'User is aangepast');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Userinfo  $userinfo
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Userinfo::where('id',$id)->delete();

        return Redirect::to(route('user.index'))->with('success','User deleted successfully');
    }
}

fric-frac-laravel/resources/views/user/create.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New User</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('user.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                    <p></p>
                    <strong>Person:</strong>
                    <select name="person_id" class="form-control">
                        @foreach($persons as $person)
                            <option value="{{ $person->id }}">{{ $person->firstname }}</option>
                        @endforeach
                    </select>
                    <p></p>
                    <strong>Role:</strong>
                    <select name="role_id" class="form-control">
                        @foreach($roles as $role)
                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                        @endforeach
                    </select>
                    <p></p>
                    <strong>Salt:</strong>
                    <input type="text" name="salt" class="form-control" placeholder="Salt">
                    <p></p>
                    <strong>HashedPassword:</strong>
                    <input type="text" name="hashedpassword" class="form-control" placeholder="HashedPassword">
                    <p></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

fric-frac-laravel/resources/views/user/edit.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit User</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('user.update', $item->id) }}" method="POST">
        @method('PATCH')
        @csrf
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" value="{{ $item->name }}">
                    <p></p>
                    <strong>Person ID:</strong>
                    <select name="person_id" class="form-control">
                        @foreach($persons as $person)
                            <option value="{{ $person->id }}">{{ $person->firstname }}</option>
                        @endforeach
                    </select>
                    <p></p>
                    <strong>Role ID:</strong>
                    <select name="role_id" class="form-control">
                        @foreach($roles as $role)
                            <option value="{{ $role->id }}">{{ $role->name }}</option>
                        @endforeach
                    </select>
                    <p></p>
                    <strong>Salt:</strong>
                    <input type="text" name="salt" class="form-control" value="{{ $item->salt }}">
                    <p></p>
                    <strong>HashedPassword:</strong>
                    <input type="text" name="hashedpassword" class="form-control" value="{{ $item->hashedpassword }}">
                    <p></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

fric-frac-laravel/resources/views/user/index.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 7 CRUD Fric-frac</h2>
            </div>
            <div class="pull-right">
                <a type="button" href="/" class="btn btn-primary">Home</a>
                <a class="btn btn-success" href="{{ route('user.create') }}"> Create New User</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($user as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->name }}</td>
                <td>
                    <a class="btn btn-success" href="{{ route('user.show', $item->id) }}" method="POST"> Show</a>
                    <a class="btn btn-info" href="{{ route('user.edit', $item->id) }}"> Edit</a>
                    <form action="{{ route('user.destroy', $item->id)}}" method="POST" style="display:inline-block">
                        @csrf
                        <input name="_method" type="hidden" value="DELETE">
                        <button class="btn btn-danger" type="submit"> Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
@endsection

fric-frac-laravel/resources/views/user/show.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 7 CRUD Fric-frac</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <a class="btn btn-info" href="{{ route('user.edit', $item->id) }}"> Edit</a>
    <form action="{{ route('user.destroy', $item->id)}}" method="POST" style="display:inline-block">
        @csrf
        <input name="_method" type="hidden" value="DELETE">
        <button class="btn btn-danger" type="submit"> Delete</button>
    </form>
    <p></p>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <td>{{ $item->id }}</td>

        </tr>
        <tr>
            <th>Name</th>
            <td>{{ $item->name }}</td>
        </tr>
        <tr>
            <th>Person ID</th>
            <td>{{ $item->person_id }}</td>
        </tr>
        <tr>
            <th>Role ID</th>
            <td>{{ $item->role_id }}</td>
        </tr>
        <tr>
            <th>Salt</th>
            <td>{{ $item->salt }}</td>
        </tr>
        <tr>
            <th>HashedPassword</th>
            <td>{{ $item->hashedpassword }}</td>
        </tr>
    </table>
@endsection